name: Manual Windows Build

on:
  workflow_dispatch:
    inputs:
      buildtype:
        description: 'Build Configuration Type'
        required: true
        default: 'RelWithDebInfo'
        type: choice
        options:
          - Debug
          - RelWithDebInfo
          - MinSizeRel

jobs:
  build-windows:
    name: Build Windows Voice Client (${{ github.event.inputs.buildtype }})
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            git
            make
            unzip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-sqlite3
            mingw-w64-x86_64-curl
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-gtkmm3
            mingw-w64-x86_64-libhandy
            mingw-w64-x86_64-opus
            mingw-w64-x86_64-libsodium
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-spdlog

      - name: Configure and Build
        run: |
          cmake -GNinja -Bbuild -DCMAKE_BUILD_TYPE=${{ github.event.inputs.buildtype }} -DCMAKE_CXX_FLAGS="-Wl,--default-image-base-low"
          cmake --build build

      - name: Package Release Artifact
        run: |
          artifact_dir=build/artifactdir/voice-client-win64
          mkdir -p ${artifact_dir}/bin ${artifact_dir}/etc/ssl/certs ${artifact_dir}/lib ${artifact_dir}/share/glib-2.0/schemas
          
          # Copy executable
          cp build/*.exe ${artifact_dir}/bin/
          
          # Copy dependencies
          cp /mingw64/etc/ssl/certs/ca-bundle.crt ${artifact_dir}/etc/ssl/certs/
          cp -r /mingw64/lib/gdk-pixbuf-2.0 ${artifact_dir}/lib/
          cp -r res/css res/res res/fonts ${artifact_dir}/bin/
          cp /mingw64/share/glib-2.0/schemas/gschemas.compiled ${artifact_dir}/share/glib-2.0/schemas/
          
          # Copy runtime DLL dependencies
          cat "ci/msys-deps.txt" | sed 's/\r$//' | xargs -I % cp /mingw64% ${artifact_dir}/bin/ || :
          cp /usr/bin/msys-ffi-8.dll ${artifact_dir}/bin/libffi-8.dll || :
          
          # Setup icon caches and themes
          mkdir -p ${artifact_dir}/share/icons/Adwaita
          cd ${artifact_dir}/share/icons/Adwaita
          mkdir -p 16x16/actions 24x24/actions 32x32/actions 48x48/actions 64x64/actions 96x96/actions scalable/actions
          mkdir -p 16x16/devices 24x24/devices 32x32/devices 48x48/devices 64x64/devices 96x96/devices scalable/devices
          mkdir -p 16x16/status 24x24/status 32x32/status 48x48/status 64x64/status 96x96/status scalable/status
          cd ${GITHUB_WORKSPACE}
          
          # Fetch theme
          wget https://github.com/rtlewis1/GTK/archive/refs/heads/Material-Black-Colors-Desktop.zip
          unzip Material-Black-Colors-Desktop.zip 'GTK-Material-Black-Colors-Desktop/Material-Black-Cherry/**/*'
          mkdir -p ${artifact_dir}/share/themes
          mv ./GTK-Material-Black-Colors-Desktop/Material-Black-Cherry ${artifact_dir}/share/themes/Material-Black-Cherry
          cp -r ci/tree/. ${artifact_dir}/
          
          cp ci/gtk-for-windows/gtk-nsis-pack/share/icons/Adwaita/index.theme ${artifact_dir}/share/icons/Adwaita/index.theme || :
          cat "ci/used-icons.txt" | sed 's/\r$//' | xargs -I % cp ci/gtk-for-windows/gtk-nsis-pack/share/icons/Adwaita/16x16/%.symbolic.png ${artifact_dir}/share/icons/Adwaita/16x16/%.symbolic.png || :
          cat "ci/used-icons.txt" | sed 's/\r$//' | xargs -I % cp ci/gtk-for-windows/gtk-nsis-pack/share/icons/Adwaita/24x24/%.symbolic.png ${artifact_dir}/share/icons/Adwaita/24x24/%.symbolic.png || :
          cat "ci/used-icons.txt" | sed 's/\r$//' | xargs -I % cp ci/gtk-for-windows/gtk-nsis-pack/share/icons/Adwaita/32x32/%.symbolic.png ${artifact_dir}/share/icons/Adwaita/32x32/%.symbolic.png || :
          cat "ci/used-icons.txt" | sed 's/\r$//' | xargs -I % cp ci/gtk-for-windows/gtk-nsis-pack/share/icons/Adwaita/48x48/%.symbolic.png ${artifact_dir}/share/icons/Adwaita/48x48/%.symbolic.png || :
          cat "ci/used-icons.txt" | sed 's/\r$//' | xargs -I % cp ci/gtk-for-windows/gtk-nsis-pack/share/icons/Adwaita/64x64/%.symbolic.png ${artifact_dir}/share/icons/Adwaita/64x64/%.symbolic.png || :
          cat "ci/used-icons.txt" | sed 's/\r$//' | xargs -I % cp ci/gtk-for-windows/gtk-nsis-pack/share/icons/Adwaita/96x96/%.symbolic.png ${artifact_dir}/share/icons/Adwaita/96x96/%.symbolic.png || :
          cat "ci/used-icons.txt" | sed 's/\r$//' | xargs -I % cp ci/gtk-for-windows/gtk-nsis-pack/share/icons/Adwaita/scalable/%.svg ${artifact_dir}/share/icons/Adwaita/scalable/%.svg || :
          
          cd ${artifact_dir}/share/icons/Adwaita
          gtk-update-icon-cache . || :

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: voice-client-win64-${{ github.event.inputs.buildtype }}
          path: build/artifactdir/voice-client-win64
